=== WFIOST/H3VR-Mod-Installer-Database/Database/MiInfoSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "ModInstallerID": {
      "type": "string"
    },
    "GameID": {
      "type": "string"
    },
    "GameName": {
      "type": "string"
    },
    "GameWebsite": {
      "type": "string"
    },
    "GameSteamID": {
      "type": "string"
    },
    "GameAuthors": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "DatabaseFiles": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "GameModdingWebsite": {
      "type": "string"
    }
  },
  "required": [
    "ModInstallerID",
    "GameID",
    "GameName",
    "GameWebsite",
    "GameSteamID",
    "GameAuthors",
    "DatabaseFiles",
    "GameModdingWebsite"
  ]
}

=== WFIOST/H3VR-Mod-Installer-Database/Database/H3vrMI.miInfo.json
{
  "ModInstallerID": "h3vrmodinstaller",
  "GameID": "h3vr",
  "GameName": "Hotdogs Horseshoes and Hand grenades",
  "GameWebsite": "https://store.steampowered.com/app/450540/Hot_Dogs_Horseshoes__Hand_Grenades/",
  "GameSteamID": "450540",
  "GameAuthors": [
    "Rust LTD"
  ],
  "DatabaseFiles": [
    "mapmods.json",
    "charactermods.json",
    "dependencies.json",
    "customitems.json",
    "mapmods.json"
  ],
  "GameModdingWebsite": "https://bonetome.com/h3vr/"
}
